blank_issues_enabled: false
contact_links:
  - name: General Support
    url: https://support.mantaro.site
    about: Please join our official support server for general questions. You will get your answer there much quicker.
